### ISSUE TITLE
Cell population identification using cell.csv from CellProfiler

### ISSUE THREAD

**Issue by indraadrianto** [BodenmillerGroup/neighbouRhood#8]
Hello,
Is it possible to perform cell population identification (clustering, performing tSNE/UMAP dimensional reduction, and creating marker-cluster heatmaps) using cell.csv from CellProfiler? If yes, which columns of cell.csv from CellProfiler that should be included? My idea is to add a label column to cell.csv based on the identified clusters before running the neighbouRhood analysis. Initially, I am thinking to use the identified clusters from HistoCAT as the label of cell.csv. But it seems to me that "CellId" of HistoCAT output does not correspond to "ObjectNumber" in cell.csv of CellProfiler. Hence, I don't know how to add a cluster label to cell.csv. Thank you!

**Comment by nilseling** [comment]
Hi @indraadrianto, 
sorry for the late reply. I've been working on the [imcRtools](https://github.com/BodenmillerGroup/imcRtools) package to facilitate IMC data analysis within the Bioconductor framework. Please have a look at this package and at the [Bioconductor single-cell analysis framework](https://bioconductor.org/books/release/OSCA/) to learn how to read in IMC data and how to perform clustering and spatial analysis. I'll close the issue here - please reopen one on imcRtools if anything is unclear.
Best,
Nils
